- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash_login:
    ~/.bashrc_local_before:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.hgrc_local:
    ~/.shell_local_after:
    ~/.ssh/config: ssh/config
    ~/.xlog:
    ~/.zshrc_local_before:

- shell:
  - git submodule sync --recursive
  - git update-submodules # after linking ~/.gitconfig
