- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/terminator:
      create: true
      force: true
      path: config/terminator/
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.hgrc_local:
    ~/.shell_local_after:
    ~/.ssh/config: ssh/config

- shell:
  - git submodule sync --recursive
  - git update-submodules # after linking ~/.gitconfig
