#!/usr/bin/env bash

# close system preferences to keep it from overriding stuff
osascript -e 'tell application "System Preferences" to quit'

# automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# translucent dock icons for hidden apps
defaults write com.apple.dock showhidden -bool true

# hide recent apps
defaults write com.apple.dock show-recents -bool false

# set the icon size of Dock items
defaults write com.apple.dock tilesize -int 50

# disable keyboard press and hold popup
defaults write -g ApplePressAndHoldEnabled -bool false

# fast keyboard repeat rate
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 15

# disable text correction
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticCapitalizationEnabled -bool false

# normal scroll direction
defaults write -g com.apple.swipescrolldirection -bool false

# expand print panel by default
defaults write -g PMPrintingExpandedStateForPrint -bool true
defaults write -g PMPrintingExpandedStateForPrint2 -bool true

# expand save panel by default
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# show all file extensions
defaults write -g AppleShowAllExtensions -bool true

# disable warning when changing file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# disable screenshot preview thumbnail
defaults write com.apple.screencapture show-thumbnail -bool false
