#!/usr/bin/env python3

import subprocess
import tempfile
import os


def main():
    with tempfile.TemporaryDirectory() as tmpdir, open(os.devnull, "w") as devnull:
        repo = os.path.join(tmpdir, "repo")
        env = {**os.environ, "GIT_CONFIG_GLOBAL": os.path.join(tmpdir, "gitconfig")}
        subprocess.check_call(
            ["git", "init", repo, "-b", "main"], stdout=devnull, env=env
        )
        subprocess.check_call(
            ["git", "maintenance", "start"], cwd=repo, stdout=devnull, env=env
        )


if __name__ == "__main__":
    main()
