#!/usr/bin/env python3

import subprocess
import tempfile
import os
import sys


def main():
    gitconfig_path = os.path.expanduser("~/.gitconfig")
    with open(gitconfig_path, "r") as f:
        old_gitconfig = f.read()
    with tempfile.TemporaryDirectory() as tmpdir, open(os.devnull, "w") as devnull:
        subprocess.check_call(["git", "init"], cwd=tmpdir, stdout=devnull)
        try:
            subprocess.check_call(
                ["git", "maintenance", "start"], cwd=tmpdir, stdout=devnull
            )
        finally:
            subprocess.check_call(
                ["git", "maintenance", "unregister", "--force"],
                cwd=tmpdir,
                stdout=devnull,
            )
    with open(gitconfig_path, "r") as f:
        new_gitconfig = f.read()
    if new_gitconfig != old_gitconfig:
        print("~/.gitconfig has changed", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
