#!/usr/bin/env bash

if [ -L ~/.ssh/config ]; then
    rm ~/.ssh/config
fi

mkdir -p ~/.ssh

cat <<EOF > ~/.ssh/config
# BEGIN xai-devbox-config include (managed by explorer)
Include /Users/aathalye/.ssh/xai-devbox-config
# END xai-devbox-config include (managed by explorer)

# START FORMAL-MANAGED BLOCK
# Do not hand-edit this section.
Include ~/.formal/ssh_config
# END FORMAL-MANAGED BLOCK

# Added by OrbStack: 'orb' SSH host for Linux machines
# This only works if it's at the top of ssh_config (before any Host blocks).
Include ~/.orbstack/ssh/config

Include ~/.ssh/config_main
EOF

chmod 600 ~/.ssh/config
