MACBOOK_MONITOR = 'Color LCD'

LAB_LEFT_MONITOR = 'HP ZR2740w'
LAB_RIGHT_MONITOR = 'DELL P2715Q'

HOME_MONITOR_MAIN = 'DELL ST2420L'
HOME_MONITOR_SECONDARY = 'Acer X193W+'

IDEs = {
  'Emacs',
  'DrRacket',
}
