MACBOOK_MONITOR = 'Built-in Retina Display'

LAB_LEFT_MONITOR = 'HP ZR2740w'
LAB_RIGHT_MONITOR = 'DELL P2715Q'

DORM_MONITOR = 'DELL U3223QE'

HOME_MONITOR = 'U28E590'

CLEANLAB_MONITOR = 'LG ULTRAFINE'

IDEs = {
  'Emacs',
  'DrRacket',
}
